CREATE TABLE "flights" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid,
	"status" text DEFAULT 'pending' NOT NULL,
	"error_code" text,
	"source_format" text NOT NULL,
	"raw_object_key" text NOT NULL,
	"track_object_key" text,
	"preview_object_key" text,
	"device" text,
	"pilot_name_raw" text,
	"glider_raw" text,
	"glider_id" uuid,
	"takeoff_site_id" uuid,
	"landing_site_id" uuid,
	"started_at" timestamp with time zone,
	"ended_at" timestamp with time zone,
	"duration_s" integer,
	"local_date" date,
	"altitude_source" text,
	"max_alt_m" integer,
	"min_alt_m" integer,
	"takeoff_alt_m" integer,
	"landing_alt_m" integer,
	"max_agl_m" integer,
	"total_gain_m" integer,
	"distance_track_m" integer,
	"distance_straight_m" integer,
	"max_climb_ms" numeric(4, 2),
	"max_sink_ms" numeric(4, 2),
	"max_speed_ms" numeric(5, 2),
	"avg_speed_ms" numeric(5, 2),
	"thermal_count" integer,
	"avg_climb_ms" numeric(4, 2),
	"avg_glide_ratio" numeric(6, 2),
	"analysis_level" text,
	"wind_dir_deg" integer,
	"wind_speed_ms" numeric(4, 2),
	"xc_type" text,
	"xc_distance_m" integer,
	"xc_score" numeric(7, 2),
	"xc_rules" text,
	"xc_is_optimal" boolean,
	"xc_turnpoints" jsonb,
	"track_simplified" geography(LineStringZM,4326),
	"bbox" geography(Polygon,4326),
	"title" text,
	"description" text,
	"privacy" text DEFAULT 'unlisted' NOT NULL,
	"share_token" text,
	"view_count" integer DEFAULT 0 NOT NULL,
	"like_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "flights_share_token_unique" UNIQUE("share_token"),
	CONSTRAINT "flights_status_check" CHECK ("flights"."status" IN ('pending', 'parsing', 'analyzing', 'ready', 'failed')),
	CONSTRAINT "flights_source_format_check" CHECK ("flights"."source_format" IN ('igc', 'gpx', 'kml', 'fit', 'csv')),
	CONSTRAINT "flights_altitude_source_check" CHECK ("flights"."altitude_source" IN ('baro', 'gnss')),
	CONSTRAINT "flights_analysis_level_check" CHECK ("flights"."analysis_level" IN ('full', 'basic')),
	CONSTRAINT "flights_privacy_check" CHECK ("flights"."privacy" IN ('public', 'unlisted', 'private'))
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" "citext" NOT NULL,
	"username" "citext" NOT NULL,
	"display_name" text,
	"avatar_url" text,
	"home_site_id" uuid,
	"units" text DEFAULT 'metric' NOT NULL,
	"locale" text DEFAULT 'ru' NOT NULL,
	"default_privacy" text DEFAULT 'unlisted' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone,
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_units_check" CHECK ("users"."units" IN ('metric', 'imperial')),
	CONSTRAINT "users_locale_check" CHECK ("users"."locale" IN ('ru', 'en')),
	CONSTRAINT "users_default_privacy_check" CHECK ("users"."default_privacy" IN ('public', 'unlisted', 'private'))
);
--> statement-breakpoint
ALTER TABLE "flights" ADD CONSTRAINT "flights_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "flights_track_simplified_gist" ON "flights" USING gist ("track_simplified");--> statement-breakpoint
CREATE INDEX "flights_user_started_idx" ON "flights" USING btree ("user_id","started_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "flights_takeoff_site_local_date_idx" ON "flights" USING btree ("takeoff_site_id","local_date" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "flights_public_started_idx" ON "flights" USING btree ("privacy","started_at" DESC NULLS LAST) WHERE "flights"."privacy" = 'public';